### PR TITLE
Branch add assert function

### PR DESCRIPTION
**Pull request by likern**
**Why?**

Add isTruthy type-aware assert function

- [x] Tests have been added/updated
- [x] Documentation has been updated

### CODE REVIEW

**Comment by likern** [comment]
@JasonEtco If this pull request will be merged with new assert feature - could you please publish new version of actions-toolkit to npm?

**Comment by JasonEtco** [comment]
@likern 👋 can you explain what this would be used for? I'm not sure I understand the need for it in this library, it seems more like a helper method that's very specific to your use-case, but I'd love to hear more.

**Comment by likern** [comment]
> @likern 👋 can you explain what this would be used for/why its needed? I'm not sure I understand the need for it in this library, it seems more like a helper method that's very specific to your use-case, but I'd love to hear more.

Yes, of course. If we use actions-toolkit in TypeScript we want to check types and  narrow down types.

There is a common pattern for that in JavaScript: using `assert` functions. This is especially useful in scripts, where in branches we just exit with failure. And main branch for successful path.
But TypeScript can't understand that we did checks.

```ts
// get version from inputs, it has type string | undefined
const version: string | undefined = '0.63.2'
assert (version !== undefined, 'Invalid version')
const str: string = version // TypeScript didn't understand that in assert we checked types. version is still string | undefined
```
If using with available API
```ts
// get version from inputs, it has type string | undefined
const version: string | undefined = '0.63.2'
if (version === undefined) {
  tools.exit.failure('version is undefined')
}

const str: string = version // TypeScript didn't understand that common pattern. version is still string | undefined
```

For that case TypeScript added assertion control flow analysis support https://github.com/microsoft/TypeScript/pull/32695

**Comment by JasonEtco** [comment]
Thanks for that @likern. But I'm not clear on why regular old `assert` doesn't do what you want? It seems that https://github.com/microsoft/TypeScript/pull/32695 added support for TypeScript being aware of `assert` possibly exiting.

To be honest, this seems like a very specific use-case, one that I'd hesitate to add to a library like actions-toolkit. I'd recommend just using a helper function in your own app code to do the same thing:

```ts
function isTruthy (tools: Toolkit, condition: boolean, msg?: string) {
  if (!condition) {
    tools.exit.failure(msg ?? `Assertion for value ${condition} is not truthy`)
  }
}
```

**Comment by likern** [comment]
> Thanks for that @likern. But I'm not clear on why regular old `assert` doesn't do what you want? It seems that https://github.com/microsoft/TypeScript/pull/32695 added support for TypeScript being aware of `assert` possibly exiting.
> 
> To be honest, this seems like a very specific use-case, one that I'd hesitate to add to a library like actions-toolkit. I'd recommend just using a helper function in your own app code to do the same thing:
> 
> ```ts
> function isTruthy (tools: Toolkit, condition: boolean, msg?: string) {
>   if (!condition) {
>     tools.exit.failure(msg ?? `Assertion for value ${condition} is not truthy`)
>   }
> }
> ```

Yes, that's possible solution. But I've decided to make pull request exactly as exit functions merely do the same. They just wrap Node.js `process.exit()`. 

The only they do on top of that is logging messages with different log level. I thought if you've added them you wanted to have unified high-level API and, possibly, do not interact with broad low-level API.

The same intention behind assertion function. Instead of throwing exceptions as Node.js asset do, worrying about broad Node.js Assert API or fighting with type guards it allows do this in s simple way.

Not many developers know assert function doesn't reduce type. Moreover assertion functions are not well known.

But, of course, if you hesitate to accept this pull request I will use my own branch, no problems.

**Pull request closed without merging**
