### PR TITLE
Adding Actions to Usage list

### PR DESCRIPTION
**Pull request by lannonbr**
I added two of my actions which use actions-toolkit to the usage list in the README.

### CODE REVIEW

**Comment by JasonEtco** [comment]
These are awesome! Thank you for adding them to the list 🎉 ❤️ I took a look at the code and I see a couple cases where `actions-toolkit` can be used more; I'll open some PRs and then merge this in 👍

**Comment by lannonbr** [comment]
Just merged in the two PRs you made. Just as a side note, I saw you commented that this made them easier to test, and with that, I'd love to learn how to test actions in general. Is there anywhere specifically you currently know of for documentation on such. I see for shell scripts you could use Bats, but for JS scripts that are placed in actions, what would you recommend looking at?

**Comment by JasonEtco** [comment]
Sweet!

> Is there anywhere specifically you currently know of for documentation on such.

Unfortunately not - the difficulty of testing Actions is one of the main reasons I wanted to write this library. [`create-an-issue`](https://github.com/JasonEtco/create-an-issue/blob/master/entrypoint.js) is a good example of a workaround - most of the functionality is outside of the main entrypoint (see `IssueCreator`), so its easier to write tests for the actual business logic. What it doesn't do is test the entire action, in its Docker container, with all of the context of previous workflows' effects. So - not a solved problem just yet I think!

**Comment by lannonbr** [comment]
@JasonEtco Yeah it's a different workflow compared to the applications I usually write so it may take awhile to get my mind wrapped around how to test it. A scenario that may be good to look into is how serverless functions (AWS Lambda, Azure Functions, Google Cloud Functions, etc) are tested given they are kinda similar where they are activated through an event-based system.

**Comment by JasonEtco** [comment]
Agreed - I think FaaS and Actions are super similar conceptually. Lots of room for tooling there

**Pull request merged**
