### PR TITLE
Throw on missing env vars

### LINKED ISSUE #38: Throw error when requiredEnvVars are missing
:wave: @JasonEtco thanks for providing this utility, it's super helpful!

What are your thoughts on throwing an error (saying, e.g. `GitHub Actions environment unavailable`) when the required environment variables are missing? My thoughts are this would make it a little more explicit when the Actions environment isn't set, and would allow me to decide how to proceed (should I abort, or try and do something useful).

https://github.com/JasonEtco/actions-toolkit/blob/eecccc314c1bdb9991a6d59549d03907296bb6f8/src/index.ts#L142-L167

### PR DESCRIPTION
**Pull request by JasonEtco**
**Why?**

For the sake of reliability and predictability, instead of just logging missing environment variables, it now throws an error with the list.

Closes #38 
cc @swinton

**How?**

I've updated it to throw an error with the same message. This let me cleanup the test a lot which is a nice bonus.

---

- [x] Tests have been added/updated (if necessary)
- [x] Documentation has been updated (if necessary)

### CODE REVIEW

**Comment by JasonEtco** [comment]
Trying to decide what kind of Semver change this'd be 🤔 It wouldn't affect actions being used on GitHub, but might throw an error in users' tests. My inclination is to bump the patch version, but I'm worried that might cause consumers of the library's tests to fail, despite those actions working in practice. That said, I don't want to bump major versions for such a small change.

Any thoughts @swinton?

**Comment by swinton** [comment]
Yeah. Good question. I think it’s a breaking change but I understand you not wanting to bump the major version for such a small change. 

How about releasing behind a flag and bumping the minor version then removing that flag for the next major release? Just an idea.

**Comment by JasonEtco** [comment]
The flag idea makes sense @swinton. Maybe something like:

```js
new Toolkit({
  throwOnWarning: Boolean
})
```

Frankly, I'm more inclined to just hold on to this PR until shipping a new major version and just bundle them together. I'm not sure how long that'll be though 🤔 but I don't think this change needs any rush.

**Comment by swinton** [comment]
>  I don't think this change needs any rush.

Agreed :100: (FWIW) :+1:

**Comment by JasonEtco** [comment]
@swinton just for you information - I've been waiting for at least one more breaking change to get this in, and #61 has come! So I'm merging this into a v2 branch with #61, and intend to publish the two PRs as a `@beta` tag for a little bit as I try it out with some actions.

**Pull request merged**
